# config.py

# Camera configuration
CAMERA_SOURCE = 2
SHOW_FPS = True

# Auto-save configuration
SAVE_CONFIDENCE = 0.5
MOVEMENT_THRESHOLD = 30  # pixels

CONFIDENCE = 0.2
IOU_THRESHOLD = 0.5
IMG_SIZE = 640

# Classes (COCO indices)
PERSON = 0
BACKPACK = 24
HANDBAG = 26
SUITCASE = 28
CELL_PHONE = 67

DETECTION_CLASSES = [PERSON, BACKPACK, HANDBAG, SUITCASE, CELL_PHONE]

# Behavior thresholds
LOITER_TIME = 8
LOITER_MOVEMENT_THRESHOLD = 15

ABANDON_TIME = 5
ABANDON_DISTANCE = 120

PHONE_TIME = 5

SUSPICION_THRESHOLD = 3